#!/bin/sh

# Set these paths appropriately

BIN=/home/sasha/Desktop/tt/bin
CMD=/home/sasha/Desktop/tt/cmd
LIB=/home/sasha/Desktop/tt/lib

GERMANTAGGER=${CMD}/tree-tagger-german-utf8
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/german-utf8.par
PARFILE2=${LIB}/german-chunker-utf8.par
FILTER=${CMD}/filter-chunker-output-german.perl

$GERMANTAGGER $* |
perl -nae 'if ($#F==0){print}else{print "$F[0]-$F[1]\n"}' |
$TAGGER $PARFILE2 -token -sgml -eps 0.00000001 -hyphen-heuristics -quiet |
$FILTER |
$TAGGER -quiet -token -lemma -sgml $PARFILE
