#!/bin/sh

# Set these paths appropriately

BIN=/home/sasha/Desktop/tt/bin
CMD=/home/sasha/Desktop/tt/cmd
LIB=/home/sasha/Desktop/tt/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/tokenize.pl
MWL=${CMD}/mwl-lookup-greek.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/greek.par

$TOKENIZER $* |
# recognition of MWLs
$MWL |
# tagging
$TAGGER $OPTIONS $PARFILE

