#!/bin/sh

# Set these paths appropriately

BIN=/home/sasha/Desktop/tt/bin
CMD=/home/sasha/Desktop/tt/cmd
LIB=/home/sasha/Desktop/tt/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
