#!/bin/sh

# Set these paths appropriately

BIN=/home/sasha/Desktop/tt/bin
CMD=/home/sasha/Desktop/tt/cmd
LIB=/home/sasha/Desktop/tt/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize.pl
ABBR_LIST=${LIB}/french-abbreviations
PARFILE=${LIB}/french.par

$TOKENIZER -f -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
