#!/bin/sh

# Set these paths appropriately

BIN=/home/sasha/Desktop/tt/bin
CMD=/home/sasha/Desktop/tt/cmd
LIB=/home/sasha/Desktop/tt/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/french-abbreviations-utf8
PARFILE=${LIB}/french-utf8.par

$TOKENIZER -f -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
